{{- with .Values.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nms.name" $ }}
  namespace: {{ include "nms.name" $ }}
  labels:
  {{- toYaml $.Values.commonLabels | nindent 4 }}
  {{- include "nms.selectorLabels" $ | nindent 4 }}
spec:
  maxUnavailable: {{ .maxUnavailable }}
  selector:
    matchLabels:
    {{- toYaml $.Values.commonLabels | nindent 6 }}
    {{- include "nms.selectorLabels" $ | nindent 6 }}
{{- end }}
