// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockListenAndServe is a mock of ListenAndServe interface.
type MockListenAndServe struct {
	ctrl     *gomock.Controller
	recorder *MockListenAndServeMockRecorder
}

// MockListenAndServeMockRecorder is the mock recorder for MockListenAndServe.
type MockListenAndServeMockRecorder struct {
	mock *MockListenAndServe
}

// NewMockListenAndServe creates a new mock instance.
func NewMockListenAndServe(ctrl *gomock.Controller) *MockListenAndServe {
	mock := &MockListenAndServe{ctrl: ctrl}
	mock.recorder = &MockListenAndServeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenAndServe) EXPECT() *MockListenAndServeMockRecorder {
	return m.recorder
}

// CreateDevices mocks base method.
func (m *MockListenAndServe) CreateDevices(ctx context.Context) func(echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevices", ctx)
	ret0, _ := ret[0].(func(echo.Context) error)
	return ret0
}

// CreateDevices indicates an expected call of CreateDevices.
func (mr *MockListenAndServeMockRecorder) CreateDevices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevices", reflect.TypeOf((*MockListenAndServe)(nil).CreateDevices), ctx)
}

// GetAccounts mocks base method.
func (m *MockListenAndServe) GetAccounts(ctx context.Context) func(echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx)
	ret0, _ := ret[0].(func(echo.Context) error)
	return ret0
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MockListenAndServeMockRecorder) GetAccounts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockListenAndServe)(nil).GetAccounts), ctx)
}

// GetChildDeviceInformations mocks base method.
func (m *MockListenAndServe) GetChildDeviceInformations(ctx context.Context) func(echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildDeviceInformations", ctx)
	ret0, _ := ret[0].(func(echo.Context) error)
	return ret0
}

// GetChildDeviceInformations indicates an expected call of GetChildDeviceInformations.
func (mr *MockListenAndServeMockRecorder) GetChildDeviceInformations(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildDeviceInformations", reflect.TypeOf((*MockListenAndServe)(nil).GetChildDeviceInformations), ctx)
}

// GetDevices mocks base method.
func (m *MockListenAndServe) GetDevices(ctx context.Context) func(echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevices", ctx)
	ret0, _ := ret[0].(func(echo.Context) error)
	return ret0
}

// GetDevices indicates an expected call of GetDevices.
func (mr *MockListenAndServeMockRecorder) GetDevices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*MockListenAndServe)(nil).GetDevices), ctx)
}

// GetGeneralDevices mocks base method.
func (m *MockListenAndServe) GetGeneralDevices(ctx context.Context) func(echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralDevices", ctx)
	ret0, _ := ret[0].(func(echo.Context) error)
	return ret0
}

// GetGeneralDevices indicates an expected call of GetGeneralDevices.
func (mr *MockListenAndServeMockRecorder) GetGeneralDevices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralDevices", reflect.TypeOf((*MockListenAndServe)(nil).GetGeneralDevices), ctx)
}

// Healthz mocks base method.
func (m *MockListenAndServe) Healthz(ctx context.Context) func(echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthz", ctx)
	ret0, _ := ret[0].(func(echo.Context) error)
	return ret0
}

// Healthz indicates an expected call of Healthz.
func (mr *MockListenAndServeMockRecorder) Healthz(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthz", reflect.TypeOf((*MockListenAndServe)(nil).Healthz), ctx)
}
