version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/asd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/nmsd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/trsd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/noded"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/controller/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/as"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/nms"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/trs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/prometheus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/grafana"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/controller"
    schedule:
      interval: "weekly"
