// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockListenAndServe is a mock of ListenAndServe interface.
type MockListenAndServe struct {
	ctrl     *gomock.Controller
	recorder *MockListenAndServeMockRecorder
}

// MockListenAndServeMockRecorder is the mock recorder for MockListenAndServe.
type MockListenAndServeMockRecorder struct {
	mock *MockListenAndServe
}

// NewMockListenAndServe creates a new mock instance.
func NewMockListenAndServe(ctrl *gomock.Controller) *MockListenAndServe {
	mock := &MockListenAndServe{ctrl: ctrl}
	mock.recorder = &MockListenAndServeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenAndServe) EXPECT() *MockListenAndServeMockRecorder {
	return m.recorder
}

// Serve mocks base method.
func (m *MockListenAndServe) Serve(ctx context.Context, addrPort string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Serve", ctx, addrPort)
}

// Serve indicates an expected call of Serve.
func (mr *MockListenAndServeMockRecorder) Serve(ctx, addrPort interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockListenAndServe)(nil).Serve), ctx, addrPort)
}
