FROM golang:1.25 AS builder
WORKDIR /app
COPY ./controller/api .
ENV GO111MODULE on
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o server ./cmd/server && \
    chmod +x /app/server

FROM alpine:latest AS production
ENV TZ=Asia/Tokyo
RUN apk --no-cache add tzdata
WORKDIR /app
COPY --from=builder /app/server .
CMD [ "./server" ]
