// Code generated by MockGen. DO NOT EDIT.
// Source: redis.go
//
// Generated by this command:
//
//	mockgen -source=redis.go -destination=mock_redis.go -package=repository -self_package=github.com/Pluslab/cyphonic/dsd/repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/Pluslab/cyphonic/dsd/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisClient is a mock of RedisClient interface.
type MockRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientMockRecorder
	isgomock struct{}
}

// MockRedisClientMockRecorder is the mock recorder for MockRedisClient.
type MockRedisClientMockRecorder struct {
	mock *MockRedisClient
}

// NewMockRedisClient creates a new mock instance.
func NewMockRedisClient(ctrl *gomock.Controller) *MockRedisClient {
	mock := &MockRedisClient{ctrl: ctrl}
	mock.recorder = &MockRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClient) EXPECT() *MockRedisClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisClient)(nil).Close))
}

// CreateOrUpdatePathInformation mocks base method.
func (m *MockRedisClient) CreateOrUpdatePathInformation(ctx context.Context, pathID *entity.ID, initiatorNodeAddress, responderNodeAddress *entity.NodeAddress, tunnelKey []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdatePathInformation", ctx, pathID, initiatorNodeAddress, responderNodeAddress, tunnelKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdatePathInformation indicates an expected call of CreateOrUpdatePathInformation.
func (mr *MockRedisClientMockRecorder) CreateOrUpdatePathInformation(ctx, pathID, initiatorNodeAddress, responderNodeAddress, tunnelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdatePathInformation", reflect.TypeOf((*MockRedisClient)(nil).CreateOrUpdatePathInformation), ctx, pathID, initiatorNodeAddress, responderNodeAddress, tunnelKey)
}

// GetInitiatorNodeIDByPathID mocks base method.
func (m *MockRedisClient) GetInitiatorNodeIDByPathID(ctx context.Context, pathID *entity.ID) (entity.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitiatorNodeIDByPathID", ctx, pathID)
	ret0, _ := ret[0].(entity.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInitiatorNodeIDByPathID indicates an expected call of GetInitiatorNodeIDByPathID.
func (mr *MockRedisClientMockRecorder) GetInitiatorNodeIDByPathID(ctx, pathID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitiatorNodeIDByPathID", reflect.TypeOf((*MockRedisClient)(nil).GetInitiatorNodeIDByPathID), ctx, pathID)
}

// SetInitiatorNodeIDAndResponderFQDN mocks base method.
func (m *MockRedisClient) SetInitiatorNodeIDAndResponderFQDN(ctx context.Context, pathID *entity.ID, initiatorNodeID entity.ID, responderFQDN string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInitiatorNodeIDAndResponderFQDN", ctx, pathID, initiatorNodeID, responderFQDN)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInitiatorNodeIDAndResponderFQDN indicates an expected call of SetInitiatorNodeIDAndResponderFQDN.
func (mr *MockRedisClientMockRecorder) SetInitiatorNodeIDAndResponderFQDN(ctx, pathID, initiatorNodeID, responderFQDN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInitiatorNodeIDAndResponderFQDN", reflect.TypeOf((*MockRedisClient)(nil).SetInitiatorNodeIDAndResponderFQDN), ctx, pathID, initiatorNodeID, responderFQDN)
}
