// Code generated by MockGen. DO NOT EDIT.
// Source: sqlhandler.go
//
// Generated by this command:
//
//	mockgen -source=sqlhandler.go -destination=mock_sqlhandler.go -package=repository -self_package=github.com/Pluslab/cyphonic/dsd/repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	entity "github.com/Pluslab/cyphonic/dsd/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSQLHandler is a mock of SQLHandler interface.
type MockSQLHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSQLHandlerMockRecorder
	isgomock struct{}
}

// MockSQLHandlerMockRecorder is the mock recorder for MockSQLHandler.
type MockSQLHandlerMockRecorder struct {
	mock *MockSQLHandler
}

// NewMockSQLHandler creates a new mock instance.
func NewMockSQLHandler(ctrl *gomock.Controller) *MockSQLHandler {
	mock := &MockSQLHandler{ctrl: ctrl}
	mock.recorder = &MockSQLHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLHandler) EXPECT() *MockSQLHandlerMockRecorder {
	return m.recorder
}

// GetNodeInformationAndNodeAddressByFQDN mocks base method.
func (m *MockSQLHandler) GetNodeInformationAndNodeAddressByFQDN(fqdn string) (entity.NodeInformation, entity.NodeAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeInformationAndNodeAddressByFQDN", fqdn)
	ret0, _ := ret[0].(entity.NodeInformation)
	ret1, _ := ret[1].(entity.NodeAddress)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNodeInformationAndNodeAddressByFQDN indicates an expected call of GetNodeInformationAndNodeAddressByFQDN.
func (mr *MockSQLHandlerMockRecorder) GetNodeInformationAndNodeAddressByFQDN(fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeInformationAndNodeAddressByFQDN", reflect.TypeOf((*MockSQLHandler)(nil).GetNodeInformationAndNodeAddressByFQDN), fqdn)
}

// GetNodeInformationAndNodeAddressByNodeID mocks base method.
func (m *MockSQLHandler) GetNodeInformationAndNodeAddressByNodeID(nodeID string) (entity.NodeInformation, entity.NodeAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeInformationAndNodeAddressByNodeID", nodeID)
	ret0, _ := ret[0].(entity.NodeInformation)
	ret1, _ := ret[1].(entity.NodeAddress)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNodeInformationAndNodeAddressByNodeID indicates an expected call of GetNodeInformationAndNodeAddressByNodeID.
func (mr *MockSQLHandlerMockRecorder) GetNodeInformationAndNodeAddressByNodeID(nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeInformationAndNodeAddressByNodeID", reflect.TypeOf((*MockSQLHandler)(nil).GetNodeInformationAndNodeAddressByNodeID), nodeID)
}
