// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock_handler.go -package=usecase -self_package=github.com/Pluslab/cyphonic/dsd/usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	errgroup "golang.org/x/sync/errgroup"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandlePackets mocks base method.
func (m *MockHandler) HandlePackets(ctx context.Context, receivePacketQueue, sendPacketQueue chan PacketQueue, errGroup *errgroup.Group) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandlePackets", ctx, receivePacketQueue, sendPacketQueue, errGroup)
}

// HandlePackets indicates an expected call of HandlePackets.
func (mr *MockHandlerMockRecorder) HandlePackets(ctx, receivePacketQueue, sendPacketQueue, errGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePackets", reflect.TypeOf((*MockHandler)(nil).HandlePackets), ctx, receivePacketQueue, sendPacketQueue, errGroup)
}

// ReceivePackets mocks base method.
func (m *MockHandler) ReceivePackets(ctx context.Context, receivePacketQueue chan PacketQueue, errGroup *errgroup.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceivePackets", ctx, receivePacketQueue, errGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceivePackets indicates an expected call of ReceivePackets.
func (mr *MockHandlerMockRecorder) ReceivePackets(ctx, receivePacketQueue, errGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceivePackets", reflect.TypeOf((*MockHandler)(nil).ReceivePackets), ctx, receivePacketQueue, errGroup)
}

// Run mocks base method.
func (m *MockHandler) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockHandlerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockHandler)(nil).Run), ctx)
}

// SendPackets mocks base method.
func (m *MockHandler) SendPackets(ctx context.Context, sendPacketQueue chan PacketQueue, errGroup *errgroup.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPackets", ctx, sendPacketQueue, errGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPackets indicates an expected call of SendPackets.
func (mr *MockHandlerMockRecorder) SendPackets(ctx, sendPacketQueue, errGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPackets", reflect.TypeOf((*MockHandler)(nil).SendPackets), ctx, sendPacketQueue, errGroup)
}
