{{- with .Values.hpa }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "as.name" $ }}
  namespace: {{ include "as.name" $ }}
  labels:
  {{- toYaml $.Values.commonLabels | nindent 4 }}
  {{- include "as.selectorLabels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "as.name" $ }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics: {{ toYaml .metrics | nindent 4 }}
  behavior: {{ toYaml .behavior | nindent 4 }}
{{- end }}
