{{- with .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "as.name" $ }}
  labels:
  {{- toYaml $.Values.commonLabels | nindent 4 }}
  {{- include "as.selectorLabels" $ | nindent 4 }}
type: {{ .type }}
data: {{ toYaml .data | nindent 4 }}
{{- end }}
