// Code generated by MockGen. DO NOT EDIT.
// Source: bucket_client.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBucketClient is a mock of BucketClient interface.
type MockBucketClient struct {
	ctrl     *gomock.Controller
	recorder *MockBucketClientMockRecorder
}

// MockBucketClientMockRecorder is the mock recorder for MockBucketClient.
type MockBucketClientMockRecorder struct {
	mock *MockBucketClient
}

// NewMockBucketClient creates a new mock instance.
func NewMockBucketClient(ctrl *gomock.Controller) *MockBucketClient {
	mock := &MockBucketClient{ctrl: ctrl}
	mock.recorder = &MockBucketClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketClient) EXPECT() *MockBucketClientMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockBucketClient) Read(bucketName, objectKey string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", bucketName, objectKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockBucketClientMockRecorder) Read(bucketName, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockBucketClient)(nil).Read), bucketName, objectKey)
}
