// Code generated by MockGen. DO NOT EDIT.
// Source: sqlhandler.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/Pluslab/cyphonic/asd/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockSQLHandler is a mock of SQLHandler interface.
type MockSQLHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSQLHandlerMockRecorder
}

// MockSQLHandlerMockRecorder is the mock recorder for MockSQLHandler.
type MockSQLHandlerMockRecorder struct {
	mock *MockSQLHandler
}

// NewMockSQLHandler creates a new mock instance.
func NewMockSQLHandler(ctrl *gomock.Controller) *MockSQLHandler {
	mock := &MockSQLHandler{ctrl: ctrl}
	mock.recorder = &MockSQLHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLHandler) EXPECT() *MockSQLHandlerMockRecorder {
	return m.recorder
}

// GetCacheInformation mocks base method.
func (m *MockSQLHandler) GetCacheInformation(arg0 context.Context, arg1 string) (entity.CacheInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheInformation", arg0, arg1)
	ret0, _ := ret[0].(entity.CacheInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheInformation indicates an expected call of GetCacheInformation.
func (mr *MockSQLHandlerMockRecorder) GetCacheInformation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheInformation", reflect.TypeOf((*MockSQLHandler)(nil).GetCacheInformation), arg0, arg1)
}

// GetDevice mocks base method.
func (m *MockSQLHandler) GetDevice(arg0 context.Context, arg1 entity.LoginRequest) (entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", arg0, arg1)
	ret0, _ := ret[0].(entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockSQLHandlerMockRecorder) GetDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockSQLHandler)(nil).GetDevice), arg0, arg1)
}

// SetNodeInformation mocks base method.
func (m *MockSQLHandler) SetNodeInformation(arg0 context.Context, arg1 entity.LoginRequest, arg2 entity.LoginResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNodeInformation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNodeInformation indicates an expected call of SetNodeInformation.
func (mr *MockSQLHandlerMockRecorder) SetNodeInformation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeInformation", reflect.TypeOf((*MockSQLHandler)(nil).SetNodeInformation), arg0, arg1, arg2)
}
