// Code generated by MockGen. DO NOT EDIT.
// Source: certificate_store.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCertificateStore is a mock of CertificateStore interface.
type MockCertificateStore struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateStoreMockRecorder
}

// MockCertificateStoreMockRecorder is the mock recorder for MockCertificateStore.
type MockCertificateStoreMockRecorder struct {
	mock *MockCertificateStore
}

// NewMockCertificateStore creates a new mock instance.
func NewMockCertificateStore(ctrl *gomock.Controller) *MockCertificateStore {
	mock := &MockCertificateStore{ctrl: ctrl}
	mock.recorder = &MockCertificateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateStore) EXPECT() *MockCertificateStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCertificateStore) Get(certificateType string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", certificateType)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCertificateStoreMockRecorder) Get(certificateType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCertificateStore)(nil).Get), certificateType)
}

// Set mocks base method.
func (m *MockCertificateStore) Set(fqdn, rootCertName, accessKey, secretKey, region, endPoint, bucketName, certificateLocation string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", fqdn, rootCertName, accessKey, secretKey, region, endPoint, bucketName, certificateLocation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCertificateStoreMockRecorder) Set(fqdn, rootCertName, accessKey, secretKey, region, endPoint, bucketName, certificateLocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCertificateStore)(nil).Set), fqdn, rootCertName, accessKey, secretKey, region, endPoint, bucketName, certificateLocation)
}
