// Code generated by MockGen. DO NOT EDIT.
// Source: tlsconn.go

// Package repository is a generated GoMock package.
package repository

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTLSListener is a mock of TLSListener interface.
type MockTLSListener struct {
	ctrl     *gomock.Controller
	recorder *MockTLSListenerMockRecorder
}

// MockTLSListenerMockRecorder is the mock recorder for MockTLSListener.
type MockTLSListenerMockRecorder struct {
	mock *MockTLSListener
}

// NewMockTLSListener creates a new mock instance.
func NewMockTLSListener(ctrl *gomock.Controller) *MockTLSListener {
	mock := &MockTLSListener{ctrl: ctrl}
	mock.recorder = &MockTLSListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTLSListener) EXPECT() *MockTLSListenerMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockTLSListener) Accept() (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept")
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockTLSListenerMockRecorder) Accept() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockTLSListener)(nil).Accept))
}

// Close mocks base method.
func (m *MockTLSListener) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTLSListenerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTLSListener)(nil).Close))
}
