// Code generated by MockGen. DO NOT EDIT.
// Source: packet_handler.go

// Package infrastructure is a generated GoMock package.
package infrastructure

import (
	context "context"
	reflect "reflect"

	entity "github.com/Pluslab/cyphonic/asd/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockPacketHandler is a mock of PacketHandler interface.
type MockPacketHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPacketHandlerMockRecorder
}

// MockPacketHandlerMockRecorder is the mock recorder for MockPacketHandler.
type MockPacketHandlerMockRecorder struct {
	mock *MockPacketHandler
}

// NewMockPacketHandler creates a new mock instance.
func NewMockPacketHandler(ctrl *gomock.Controller) *MockPacketHandler {
	mock := &MockPacketHandler{ctrl: ctrl}
	mock.recorder = &MockPacketHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketHandler) EXPECT() *MockPacketHandlerMockRecorder {
	return m.recorder
}

// CreateLoginResponse mocks base method.
func (m *MockPacketHandler) CreateLoginResponse(ctx context.Context) (*entity.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoginResponse", ctx)
	ret0, _ := ret[0].(*entity.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoginResponse indicates an expected call of CreateLoginResponse.
func (mr *MockPacketHandlerMockRecorder) CreateLoginResponse(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoginResponse", reflect.TypeOf((*MockPacketHandler)(nil).CreateLoginResponse), ctx)
}

// ReCreateLoginRequest mocks base method.
func (m *MockPacketHandler) ReCreateLoginRequest(arg0 context.Context, arg1 *entity.LoginRequest, arg2 []byte, arg3 int) *entity.LoginRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReCreateLoginRequest", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*entity.LoginRequest)
	return ret0
}

// ReCreateLoginRequest indicates an expected call of ReCreateLoginRequest.
func (mr *MockPacketHandlerMockRecorder) ReCreateLoginRequest(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReCreateLoginRequest", reflect.TypeOf((*MockPacketHandler)(nil).ReCreateLoginRequest), arg0, arg1, arg2, arg3)
}

// Unmarshal mocks base method.
func (m *MockPacketHandler) Unmarshal(ctx context.Context, buf []byte, length int) (*entity.LoginRequest, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", ctx, buf, length)
	ret0, _ := ret[0].(*entity.LoginRequest)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockPacketHandlerMockRecorder) Unmarshal(ctx, buf, length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockPacketHandler)(nil).Unmarshal), ctx, buf, length)
}
