// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	context "context"
	reflect "reflect"

	gateway "github.com/Pluslab/cyphonic/controller/api/adapter/gateway"
	gomock "github.com/golang/mock/gomock"
)

// MockGormClientFactory is a mock of GormClientFactory interface.
type MockGormClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockGormClientFactoryMockRecorder
}

// MockGormClientFactoryMockRecorder is the mock recorder for MockGormClientFactory.
type MockGormClientFactoryMockRecorder struct {
	mock *MockGormClientFactory
}

// NewMockGormClientFactory creates a new mock instance.
func NewMockGormClientFactory(ctrl *gomock.Controller) *MockGormClientFactory {
	mock := &MockGormClientFactory{ctrl: ctrl}
	mock.recorder = &MockGormClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGormClientFactory) EXPECT() *MockGormClientFactoryMockRecorder {
	return m.recorder
}

// NewClient mocks base method.
func (m *MockGormClientFactory) NewClient(ctx context.Context) (*gateway.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", ctx)
	ret0, _ := ret[0].(*gateway.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockGormClientFactoryMockRecorder) NewClient(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockGormClientFactory)(nil).NewClient), ctx)
}
