name: web-reviewdog

on:
  push:
    branches:
      - "main"
      - "develop"
      - "!dependabot/**"
    paths:
      - ".github/workflows/web-reviewdog.yaml"
      - "controller/web/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "hotfix/**"
      - "**"
      - "!dependabot/**"
    paths:
      - ".github/workflows/web-reviewdog.yaml"
      - "controller/web/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: controller/web/package-lock.json
      - run: cd ./controller/web && npm ci
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run ESLint with reviewdog for code review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./controller/web
          npm run lint | reviewdog -f=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
      - name: Run TypeScript static analysis for code review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./controller/web
          tsc --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error=true
